name: Shepower
description: A new Flutter project.
publish_to: 'none'
# version: 0.1.0
version: 0.1.2+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  razorpay_flutter: ^1.3.3
  url_launcher: ^6.2.2
  device_info_plus: ^9.1.1
  google_fonts: ^6.1.0
  google_ml_kit: ^0.16.2
  image_picker: ^0.8.5+3
  image: ^3.2.0
  camera: ^0.10.5+3
  image_editor: ^1.3.0
  country_list_pick: ^1.0.1+6
  intl: ^0.19.0
  permission_handler: ^11.0.1
  flutter_secure_storage: ^9.0.0
  googleapis_auth: ^1.4.1
  webview_flutter: ^4.2.4
  firebase_core: ^2.15.1
  file_picker: ^6.0.0
  photo_manager: ^2.7.1
  custom_gallery_display: ^0.5.0
  image_cropper: ^5.0.0
  image_crop: ^0.4.1
  iconsax: ^0.0.8
  firebase_auth: ^4.9.0
  flutter_typeahead: ^4.7.0
  shared_preferences: ^2.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0  
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  flutter_dialogs: ^3.0.0
  fluttertoast: ^8.2.2
  socket_io_client: ^2.0.3+1
  sqflite: ^2.3.0
  web_socket_channel: ^2.4.0
  get: ^4.6.6
  record: ^4.0.0 
  audio_waveforms: ^1.0.4
  flutter_tflite: ^1.0.1
  device_info: ^2.0.3
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.3
  flutter_screenutil: ^5.9.0
  gradient_borders: ^1.0.0
  just_audio: ^0.9.35
  video_player: ^2.7.2
  animations: ^2.0.8
  shimmer: ^2.0.0
  http_parser: ^4.0.2
  audioplayers: ^5.2.0
  share_plus: ^7.2.1
  pull_to_refresh: ^2.0.0
  flutter_pin_code_fields: ^2.2.0
  flutter_pdfview: ^1.2.7
  dio: ^4.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  fast_contacts: ^3.1.2
  contacts_service: ^0.6.3
  firebase_dynamic_links: ^5.4.8
  comment_box: ^0.0.18
  stylish_dialog: ^1.0.2
  google_maps_flutter: ^2.5.3
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  wave: ^0.2.2
  translator: ^1.0.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  easy_localization: any
  flutter_i18n: ^0.35.1
  expandable_text: ^2.3.0

  
 
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/Splash/shepower.png
    - assets/Welcome/
    - assets/face/
    - assets/profile/
    - assets/homedashboardicon/
    - assets/explore/
    - assets/OtherProfile/
    - assets/Event/
    - assets/ChatRoom/
    - assets/profile/edit.png
    - assets/profile/faq.png
    - assets/profile/logout.png
    - assets/Splash/shepower.png
    - assets/notification1.mp3
    - assets/notification2.mp3
    - assets/translations/
   
  


  fonts:
    - family: LavishlyYours
      fonts:
        - asset: assets/fonts/LavishlyYours-Regular.ttf
    - family: MervaleScript
      fonts:
        - asset: assets/fonts/MervaleScript-Regular.ttf
    - family: Fontanero 
      fonts:
        - asset: assets/fonts/fontanero.ttf
    