// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mRil1nisNaJo0JkwCT9ciQ7wIN9ARhA',
    appId: '1:538011408275:web:4c48b1fef6598994463a66',
    messagingSenderId: '538011408275',
    projectId: 'shepower1-d657d',
    authDomain: 'shepower1-d657d.firebaseapp.com',
    storageBucket: 'shepower1-d657d.appspot.com',
    measurementId: 'G-T2WYT1M06J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4S5Q2O3YHbTeSHikneAC9KjJanbBWPY',
    appId: '1:538011408275:android:c58100c2edd073d5463a66',
    messagingSenderId: '538011408275',
    projectId: 'shepower1-d657d',
    storageBucket: 'shepower1-d657d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3OSVxCOzVl_euFUS0YBRXlY-CUICwMKs',
    appId: '1:538011408275:ios:7a43e0a178f69b1a463a66',
    messagingSenderId: '538011408275',
    projectId: 'shepower1-d657d',
    storageBucket: 'shepower1-d657d.appspot.com',
    androidClientId:
        '538011408275-ei5v2pisb1dhrjhtc9vhr2i3prohjae2.apps.googleusercontent.com',
    iosClientId:
        '538011408275-8tj5ppc4tcs2cergijqjidtkbeka4v5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.shepower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3OSVxCOzVl_euFUS0YBRXlY-CUICwMKs',
    appId: '1:538011408275:ios:ddcd8fd9ff59311d463a66',
    messagingSenderId: '538011408275',
    projectId: 'shepower1-d657d',
    storageBucket: 'shepower1-d657d.appspot.com',
    androidClientId:
        '538011408275-ei5v2pisb1dhrjhtc9vhr2i3prohjae2.apps.googleusercontent.com',
    iosClientId:
        '538011408275-mi94vkr11721e1mvp3gk97se8is487fu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shepower.RunnerTests',
  );
}
